app/src/main/java/ru/practicum/android/diploma/App.kt
app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModel.kt

Создана общая конфигурация для внедрения зависимостей
Создан класс App

DI конфигурация Koin

---

app/src/main/AndroidManifest.xml
app/src/main/java/ru/practicum/android/diploma/data/NetworkClient.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/Response.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacanciesRequest.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacanciesResponse.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HHApiClient.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HhApi.kt

Добавил клиент для работы с запросом "/vacancies"
Используется токен по ключу HH_ACCESS_TOKEN (чтобы он появился нужен файл develop.properties со строкой, напр.
hhAccessToken=my_access_token
, а также необходимо собрать проект Build->Make Proect <Ctrl+F9>
)

NetworkClient #7: Добавил клиент для работы с запросом "/vacancies"

---

app/src/main/java/ru/practicum/android/diploma/util/debouncer/Debouncer.kt
app/src/main/java/ru/practicum/android/diploma/util/extentions/DpToPxExtention.kt
app/src/main/java/ru/practicum/android/diploma/util/other/Constants.kt
app/src/main/java/ru/practicum/android/diploma/util/other/StringUtil.kt

Добавлены утилиты:
1. Дебаунсер
2. Скругление углов изображений
3. Утилита для добавления склонения к окончаниям в слове "вакансия"
4. Глобальные константы

Задача № 9 (добавление утилит)

---

app/src/main/java/ru/practicum/android/diploma/data/dto/AreaDto.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/BaseDto.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt

Обновлен класс VacancyDto,
создан класс AreaDTO

DTO-модели данных

---

app/src/main/java/ru/practicum/android/diploma/data/dto/AreaDto.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Area.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Vacancy.kt

Подготовлены доменные модели Vacancy и Area
Созданы функции для конвертации из DTO в Domain-модели

Доменные модели Vacancy и Area

---

app/src/main/AndroidManifest.xml
app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt

+ В Манифесте приписано имя класса приложения

Ориентация приложения = portrait

---

app/src/main/res/drawable/mask.xml
app/src/main/res/layout/fragment_team.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Со шрифтами до конца не разобрался - как будто не очень похоже на макет.
Список команды сделал одним вью, поэтому отступы могут не соответствовать.
Все строки и размеры вынес в ресурсы. Создал ночные ресурсы цветов - black и white противоположны дневным white и black

Экран "Команда"

---

app/src/main/java/ru/practicum/android/diploma/data/dto/VacanciesResponse.kt

исправление наименования поля соответственно патерну camelCase [a-z][A-Za-z0-9] "perPage" и сериализации поля "per_page"

["detekt"] <detekt.ConstructorParameterNaming> #24 : исправление наименования

---

app/src/main/java/ru/practicum/android/diploma/data/db/AppDataBase.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/AreaTypeConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/FavoriteVacancyDbConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/dao/FavoriteVacancyDao.kt
app/src/main/java/ru/practicum/android/diploma/data/db/entity/FavoriteVacancyEntity.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HhApi.kt
app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
app/src/main/java/ru/practicum/android/diploma/util/other/Constants.kt

Добавлен DatabaseClient для избранных вакансий
Пока что не проходит проверку, так как отсутствуют элементы кода (имеются ссылки на дата классы Vacancy и Area, но сами классы не реализованы, так как еще не были залиты на ветку develop)

DatabaseClient

---

app/src/main/java/ru/practicum/android/diploma/data/db/converter/FavoriteVacancyDbConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HHApiClient.kt
app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
app/src/main/java/ru/practicum/android/diploma/util/debouncer/Debouncer.kt
app/src/main/java/ru/practicum/android/diploma/util/other/Constants.kt

Исправить замечания detekt №59

Исправить замечания detekt

---

app/src/main/java/ru/practicum/android/diploma/data/VacanciesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/converter/VacancyConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/converter/VacancyConvertor.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/AreaTypeConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/FavoriteVacancyDbConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/entity/FavoriteVacancyEntity.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/KeySkillDto.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Vacancy.kt

В сущности Вакансия добавлены поля улица, номер дома и Ключевые навыки

Добавлены новые поля Вакансии

---

app/src/main/java/ru/practicum/android/diploma/data/VacanciesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/converter/VacancyConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/FavoriteVacancyDbConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/entity/FavoriteVacancyEntity.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacanciesResponse.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDetailDto.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HHApiClient.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Vacancy.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
app/src/main/java/ru/practicum/android/diploma/presentation/search/SearchViewModel.kt

- обновил состав моделей вакансий 
- исправления падения приложения в "режиме полета"
- отображение статуса "нет интернета (поиск)"
- отображение логотипа компании
- отображение уровня зарплаты (+ отображение валюты)

Экран поиска доработка (Задача 1) #74

---

app/src/main/java/ru/practicum/android/diploma/ui/root/details/DetailsFragment.kt
app/src/main/res/layout/fragment_details.xml

Исправлено отображение логотипа компании на экране с деталями вакансий

Логотип компании

---

app/src/main/java/ru/practicum/android/diploma/presentation/search/SearchViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/search/SearchFragment.kt

- устранена проблема с отображением пустого результата
- добавлены Тосты для всех сообщений об ошибке
- исправлена работа счетчика страниц

Доработан экран «Поиск вакансий»

---

app/src/main/java/ru/practicum/android/diploma/ui/root/details/DetailsFragment.kt

Исправлено отображение ошибки на экране с деталями вакансии

Плейсхолдер в деталях вакансии

---

app/src/main/java/ru/practicum/android/diploma/data/NetworkClient.kt
app/src/main/java/ru/practicum/android/diploma/data/VacanciesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/KeySkillsTypeConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDetailDto.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HHApiClient.kt
app/src/main/java/ru/practicum/android/diploma/presentation/details/DetailsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/favorite/FavoriteScreenState.kt
app/src/main/java/ru/practicum/android/diploma/presentation/favorite/FavoriteViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/favorite/FavoritesFragment.kt

- многоуровневый if/else заменен на when
- переименованы функции
- отформатированы DTO-классы

Косметические правки

---

app/src/main/java/ru/practicum/android/diploma/data/NetworkClient.kt
app/src/main/java/ru/practicum/android/diploma/data/VacanciesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/db/converter/KeySkillsTypeConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDetailDto.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HHApiClient.kt
app/src/main/java/ru/practicum/android/diploma/presentation/details/DetailsScreenState.kt
app/src/main/java/ru/practicum/android/diploma/presentation/details/DetailsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/favorite/FavoriteScreenState.kt
app/src/main/java/ru/practicum/android/diploma/presentation/favorite/FavoriteViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/details/DetailsFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/favorite/FavoritesFragment.kt

На экране Детали вакансии выделен отдельный state под отсутствие интернет соединения

обработка состояния "нет интернета" в деталях вакансии

---

app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
app/src/main/java/ru/practicum/android/diploma/util/extentions/SalaryFormat.kt
app/src/main/res/layout/fragment_details.xml
app/src/main/res/layout/item_vacancy.xml

Пока не придумал как решить перекрытие прогресс-бара

Gh pad 117

---

app/src/main/java/ru/practicum/android/diploma/data/converter/SharedPreferencesConverterImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/shared/SharedPreferencesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/sharedPreferences/SharedPreferencesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/SharedPreferencesConverter.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/SharedPreferencesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/SharedPreferencesRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/SharedPreferencesInteractorImpl.kt

GH-PAD-144: Реализация SharedPreferences для управления параметрами фильтра

GH-PAD-144: Реализация SharedPreferences

---

app/src/main/java/ru/practicum/android/diploma/data/HhRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/converter/SharedPreferencesConverterImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/shared/SharedPreferencesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/SharedPreferencesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/SharedPreferencesRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/SharedPreferencesInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/industry/IndustryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/industry/FilterIndustry.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/industry/IndustryAdapter.kt
app/src/main/res/layout/fragment_filter_industry.xml

Изменена логика по удалению отрасли из shared preferences, добавлен flatmap в списке отраслей

Доработки логики по выбору отрасли

---

app/src/main/java/ru/practicum/android/diploma/data/FavoriteRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/presentation/favorite/FavoriteViewModel.kt

Рефакторинг отлова ошибки при обращении к локальной БД

Рефакторинг работы с избранным

---

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModul.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectCountryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectPlaceViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectRegionViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/AreaAdapter.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/AreaState.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/AreaViewHolder.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectCountryFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectPlaceFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectRegionFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/WorkPlaceState.kt
app/src/main/res/layout/fragment_select_country.xml
app/src/main/res/layout/fragment_select_place.xml
app/src/main/res/layout/fragment_select_region.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/styles.xml

Пакеты plase перемещены внутрь пакетов filter

Рефакторинг

---

app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectRegionViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/AreaAdapter.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/AreaState.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectRegionFragment.kt
app/src/main/res/layout/fragment_select_region.xml

Исправлено отображение плейсхолдеров на листе с выбором регионов

Плейсхолдер на листе с выбором регионов

---

app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectCountryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectCountryFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectPlaceFragment.kt
app/src/main/res/layout/fragment_select_country.xml

Добавлен плейсхолдер на экране выбора страны

Плейсхолдер на экране выбора страны

---

app/src/main/java/ru/practicum/android/diploma/presentation/filter/industry/IndustryScreenState.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/industry/IndustryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectCountryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectPlaceViewModel.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectRegionViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/industry/FilterIndustry.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/AreaState.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectCountryFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectPlaceFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectRegionFragment.kt

Отметил в задаче проблемы, которые удалось исправить

GH-PAD-196

---

app/src/main/java/ru/practicum/android/diploma/presentation/filter/place/SelectPlaceViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/place/SelectPlaceFragment.kt

Реализован повторный запрос данных, если ранее данные не были загружены

Повторный запрос Areas

---

app/src/main/java/ru/practicum/android/diploma/presentation/filter/industry/IndustryScreenState.kt
app/src/main/java/ru/practicum/android/diploma/presentation/filter/industry/IndustryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/industry/FilterIndustry.kt
app/src/main/java/ru/practicum/android/diploma/ui/root/filter/industry/IndustryAdapter.kt
app/src/main/res/layout/fragment_filter_industry.xml
app/src/main/res/values/strings.xml

Добавлен плейсхолдер в зависимости от введенного текста в строке поиска отрасли

Плейсхолдер в поиске отрасли
